markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Johnqing
host: johnqing.github.com
desc: 思考记录之地

book:
  - name:  JavaScript模式
    imgid: 11337059
    bid: 11506062

  - name:  基于MVC的JavaScript Web富应用开发
    imgid: 10427681
    bid: 10733304

  - name:  JavaScript语言精粹
    imgid: 3651235
    bid: 3590768
    
    
custom:
    category:
        f2e:  前端架构
        css:  css
        js:  js
        readbook:  读书笔记
    categories:
      - name:  f2e
        title: 前端架构

      - name:  css
        title: css

      - name:  js
        title: js

      - name:  readbook
        title: 读书笔记

meta:
    author:
        name: 刘卿
        email: csssnow@gmail.com
        disqus: johnqing                            # Disqus缩略标识
        gcse: 013272657981146924125:j-9xsn0usau     # Google自定义搜索标识ID
        github: johnqing                            # GitHub账号
        gravatar: fdfcf1e17124a1b949b98ddff70550a8  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址