#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#


#
# Jekyll basic configurations
#

timezoon: Asia/Hong_kong
permalink: /:title/
markdown: redcarpet
highlighter: rouge

#
# Jekyll serve settings
#


#
# Additional Markdown settings
#
redcarpet:
    extensions:
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - strikethrough
        - superscript
        - smart
        - space_after_headers
        - footnotes
        - underline

exclude:
    - README.md
    - Gruntfile.js
    - package.json
    - node_modules


#
# User defined settings
#

# Site name
name: mss

# Site description and keywords, will appear in the document meta and Atom feed subtitle
description: Mss - 相信世界始终美好。
keywords: 猫叔,mss,web前端,前端,HTML,CSS,JavaScript,js,设计

# Assets path used in templates
assets: ./assets

# Sass defined settings
sass:
    sass_dir: assets/css/_sass
    style: compressed # Enable minification
